[aws]
aws_access_key_id = "AKIARHJJNKXMDP6MPDIS"
aws_secret_access_key = "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"
region_name = "us-east-1"

[reddit]
client_id = "wh7UiZSJQ10E0mQZt93oAA"
client_secret = "ChMXPmBxdtDdUJuoo4OYhAA1e-N4XA"
user_agent = "sentiment-app by u/StillFindingMyself4"
